import Head from 'next/head'
import Image from 'next/image'

import stick from './assets/icons/stick.svg'
import Card from './components/card'

export default function Home() {
  return (
    <>
      <Head>
        <title>Estefany David | Contatos Comerciais</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex flex-col w-screen h-screen'>
        <div className="flex flex-col gap-7">
          <Card />
        </div>

        <div className="flex flex-col h-full justify-end items-center text-center">
          <p className='pb-10 text-sm'>Selecione um dos <span>contatos</span> acima</p>
        </div>

        <div className="fixed footerStick">
          <Image src={stick} alt="Tracejado no fim da página" />
        </div>
      </main>
    </>
  )
}
